name: Demo application
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.10

      - name: create virtual environment
        run: |
          python3 -m venv venv
          source venv/bin/activate
        
      - name: Install dependencies
        run: pip3 install -r requirements.txt
