name: Demo application
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: create virtual environment
        run: |
          python3 -m venv venv
          source vemv/bin/activate
        
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python -m pip install -r .github/workflows/requirements.txt